const styles = {
  page: {
    minHeight: "100vh",
    background: "linear-gradient(180deg, #fff8f6 0%, #fff2f5 50%, #fffdf8 100%)",
    color: "#4b2e2e",
    fontFamily: "Arial, sans-serif",
  },
  navbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "18px 40px",
    backgroundColor: "rgba(255,255,255,0.85)",
    backdropFilter: "blur(10px)",
    position: "sticky",
    top: 0,
    zIndex: 10,
    borderBottom: "1px solid #f0d9df",
    flexWrap: "wrap",
    gap: 12,
  },
  logo: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#b85c7a",
  },
  navLinks: {
    display: "flex",
    gap: 20,
    flexWrap: "wrap",
    alignItems: "center",
  },
  link: {
    textDecoration: "none",
    color: "#6b4b4b",
    fontWeight: 600,
  },
  cartLink: {
    textDecoration: "none",
    color: "white",
    fontWeight: 700,
    backgroundColor: "#b85c7a",
    padding: "10px 16px",
    borderRadius: 999,
  },
  heroSection: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: 30,
    alignItems: "center",
    padding: "50px 40px",
  },
  banner: {
    marginBottom: 24,
  },
  bannerText: {
    color: "#d17b88",
    textTransform: "uppercase",
    fontWeight: "bold",
    letterSpacing: 1,
  },
  heroTitle: {
    fontSize: "clamp(36px, 6vw, 58px)",
    margin: "0 0 16px",
    lineHeight: 1.1,
  },
  heroSubtitle: {
    fontSize: 18,
    lineHeight: 1.7,
    color: "#6d5a5a",
    maxWidth: 600,
  },
  heroButtons: {
    display: "flex",
    gap: 14,
    flexWrap: "wrap",
  },
  primaryButton: {
    textDecoration: "none",
    border: "none",
    backgroundColor: "#b85c7a",
    color: "white",
    padding: "13px 22px",
    borderRadius: 999,
    cursor: "pointer",
    fontSize: 15,
    fontWeight: 700,
    boxShadow: "0 10px 22px rgba(184,92,122,0.22)",
  },
  secondaryButton: {
    textDecoration: "none",
    border: "1px solid #e6b9c4",
    backgroundColor: "white",
    color: "#b85c7a",
    padding: "13px 22px",
    borderRadius: 999,
    cursor: "pointer",
    fontSize: 15,
    fontWeight: 700,
  },
  heroImageWrap: {
    display: "flex",
    justifyContent: "center",
  },
  heroImage: {
    width: "100%",
    maxWidth: 480,
    height: 520,
    objectFit: "cover",
    borderRadius: 28,
    boxShadow: "0 20px 40px rgba(0,0,0,0.10)",
  },
  section: {
    padding: "24px 40px 40px",
    textAlign: "center",
  },
  sectionTag: {
    color: "#d17b88",
    textTransform: "uppercase",
    letterSpacing: 1,
    fontWeight: "bold",
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 36,
    margin: "0 0 24px",
  },
  flavourRow: {
    display: "flex",
    justifyContent: "center",
    gap: 12,
    flexWrap: "wrap",
  },
  flavourButton: {
    padding: "12px 18px",
    borderRadius: 999,
    cursor: "pointer",
    fontWeight: 700,
    backgroundColor: "white",
  },
  highlightBox: {
    backgroundColor: "rgba(255,255,255,0.88)",
    padding: 24,
    borderRadius: 24,
    textAlign: "left",
    marginBottom: 24,
    boxShadow: "0 10px 28px rgba(0,0,0,0.05)",
  },
  description: {
    color: "#6d5a5a",
    lineHeight: 1.7,
  },
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: 20,
  },
  card: {
    backgroundColor: "white",
    borderRadius: 24,
    overflow: "hidden",
    textAlign: "left",
    boxShadow: "0 10px 28px rgba(0,0,0,0.06)",
  },
  cardImage: {
    width: "100%",
    height: 220,
    objectFit: "cover",
    display: "block",
  },
  badge: {
    display: "inline-block",
    fontWeight: "bold",
    backgroundColor: "white",
    padding: "8px 12px",
    borderRadius: 999,
    marginBottom: 12,
  },
  cardBody: {
    padding: 20,
  },
  cardTitle: {
    marginTop: 0,
    marginBottom: 10,
    fontSize: 22,
  },
  cardFooter: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 12,
  },
  quantityControl: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  quantityButton: {
    border: "none",
    color: "white",
    width: 34,
    height: 34,
    borderRadius: "50%",
    cursor: "pointer",
    fontWeight: 700,
    fontSize: 18,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  quantityValue: {
    minWidth: 20,
    textAlign: "center",
    fontWeight: 700,
    fontSize: 18,
  },
  smallButton: {
    border: "none",
    color: "white",
    padding: "10px 16px",
    borderRadius: 999,
    cursor: "pointer",
    fontWeight: 700,
  },
  galleryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
    gap: 20,
  },
  galleryCard: {
    position: "relative",
    minHeight: 320,
    borderRadius: 24,
    overflow: "hidden",
    boxShadow: "0 10px 28px rgba(0,0,0,0.06)",
  },
  galleryImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  galleryOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    padding: 18,
    color: "white",
    fontWeight: "bold",
    background: "linear-gradient(180deg, transparent, rgba(0,0,0,0.60))",
  },
  visitBoxSection: {
    padding: "0 40px 20px",
  },
  visitBox: {
    backgroundColor: "#fffaf7",
    borderRadius: 20,
    padding: 20,
    boxShadow: "0 10px 24px rgba(0,0,0,0.05)",
  },
  simplePage: {
    padding: "50px 40px",
    minHeight: "70vh",
  },
  list: {
    maxWidth: 700,
    margin: "0 auto",
    textAlign: "left",
    lineHeight: 2,
    color: "#6d5a5a",
  },
  form: {
    maxWidth: 600,
    margin: "0 auto",
    display: "grid",
    gap: 16,
  },
  input: {
    padding: 14,
    borderRadius: 14,
    border: "1px solid #e7cbd3",
    fontSize: 16,
  },
  textarea: {
    minHeight: 120,
    padding: 14,
    borderRadius: 14,
    border: "1px solid #e7cbd3",
    fontSize: 16,
    resize: "vertical",
  },
  successBox: {
    maxWidth: 600,
    margin: "20px auto 0",
    backgroundColor: "#fff7f9",
    color: "#8b4f5f",
    padding: 16,
    borderRadius: 16,
    border: "1px solid #f0d9df",
  },
  contactInfoCard: {
    maxWidth: 700,
    margin: "24px auto 0",
    backgroundColor: "#fffaf7",
    borderRadius: 24,
    padding: 24,
    boxShadow: "0 10px 24px rgba(0,0,0,0.05)",
  },
  contactLine: {
    fontSize: 18,
    color: "#6d5a5a",
    marginBottom: 12,
  },
  footer: {
    textAlign: "center",
    padding: 24,
    color: "#8a6b6b",
    borderTop: "1px solid #f0d9df",
  },
  emptyCart: {
    maxWidth: 700,
    margin: "0 auto",
    backgroundColor: "#fffaf7",
    padding: 24,
    borderRadius: 20,
    color: "#6d5a5a",
    boxShadow: "0 10px 24px rgba(0,0,0,0.05)",
  },
  cartList: {
    maxWidth: 900,
    margin: "0 auto",
    display: "grid",
    gap: 18,
  },
  cartItem: {
    display: "grid",
    gridTemplateColumns: "140px 1fr",
    gap: 18,
    alignItems: "center",
    backgroundColor: "white",
    padding: 18,
    borderRadius: 20,
    boxShadow: "0 10px 24px rgba(0,0,0,0.05)",
  },
  cartImage: {
    width: "100%",
    height: 120,
    objectFit: "cover",
    borderRadius: 16,
  },
  cartActionRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
  },
  totalBox: {
    maxWidth: 900,
    margin: "24px auto 0",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 16,
    flexWrap: "wrap",
    backgroundColor: "#fff7f9",
    padding: 20,
    borderRadius: 20,
    border: "1px solid #f0d9df",
  },
};

export default styles;